import { SidebarMenuItemModel } from "./types";

export const SIDEBAR_MENUS: SidebarMenuItemModel[] = [
  {
    id: 1,
    label: "Tableau de bord",
    url: "",
    icon: "dashboard",
    code: "dashboard",
    position: 1,
    parentMenuId: null,
    statusCode: "",
    subMenus: [],
  },
  {
    id: 2,
    label: "Services",
    url: "services",
    icon: "services",
    code: "services",
    position: 2,
    parentMenuId: null,
    statusCode: "",
    subMenus: [],
  },
  {
    id: 3,
    label: "Duplicatas",
    url: "duplicatas",
    icon: "duplicata",
    code: "duplicata",
    position: 3,
    parentMenuId: null,
    statusCode: "",
    subMenus: [],
  },
  {
    id: 4,
    label: "Cotisations",
    url: "cotisations",
    icon: "cotisations",
    code: "cotisations",
    position: 4,
    parentMenuId: null,
    statusCode: "",
    subMenus: [],
  },
  {
    id: 5,
    label: "Réclamations",
    url: "reclamations",
    icon: "reclamations",
    code: "reclamations",
    position: 5,
    parentMenuId: null,
    statusCode: "",
    subMenus: [],
  },
  {
    id: 6,
    label: "Paramètres",
    url: "settings",
    icon: "settings",
    code: "settings",
    position: 6,
    parentMenuId: null,
    statusCode: "",
    subMenus: [
      {
        id: 1,
        label: "Utilisateurs",
        url: "users",
        icon: "users",
        code: "users",
        position: 1,
        parentMenuId: null,
        statusCode: "",
        subMenus: [],
      },
      {
        id: 2,
        label: "Roles",
        url: "roles",
        icon: "roles",
        code: "roles",
        position: 1,
        parentMenuId: null,
        statusCode: "",
        subMenus: [],
      },
      {
        id: 4,
        label: "Motifs",
        url: "motifs",
        icon: "motifs",
        code: "motifs",
        position: 4,
        parentMenuId: null,
        statusCode: "",
        subMenus: [],
      },
    ],
  },
];
